### ISSUE TITLE
Rework CLI

### ISSUE THREAD

**Issue by jsqu4re** [yocurt/yogurt-yaml#1]
# CLI
Parameters:
- set identifiers e.g.: ID, REF, ADD, END -> new cli tool
- enable @ for references (e.g. names)
- enable # for references (hashtags, and e.g. topics)
- search folders and or file(s) maybe with regex -> new cli tool
- set config file e.g. `.yaml` or `.toml` -> new cli tool

-> Maybe this cli tool should be a in separate curt-cli repo 

- [x]  Create new cli repo with advanced file handling -> yocurt/yogurt-cli
- [x]  enable @ for references (e.g. names) -> #17 
- [x]  enable # for references (hashtags, and e.g. topics) -> #18 and #19 
- [x]  simplify local cli (no arg parse, no settings in this main) -> #20

**Comment by jsqu4re** [comment]
Split up into multiple issues
